### PR TITLE
Support label feature

### PR DESCRIPTION
**Pull request by cosmo0920**
Fluentd v0.12 supports label feature.
And I added keeping backward compatibility hack.

### CODE REVIEW

**Comment by cosmo0920** [comment]
ping?
In v0.14, `Fluent::Engine.emit` is forbidden and causes exceptions.

**Comment by cosmo0920** [comment]
With v0.14.9, `Fluent::Engine.emit` does not work in spec:

```log
$ bundle exec rspec spec/*_spec.rb
.....F

Failures:

  1) Fluent::EventCounterOutput output formats the counts against the provided tag
     Failure/Error: Fluent::Engine.emit(@emit_to, Time.now, tag => events)

     RuntimeError:
       BUG: use router.emit instead of Engine.emit
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/engine.rb:132:in `emit'
     # ./lib/fluent/plugin/out_eventcounter.rb:91:in `block in write'
     # ./lib/fluent/plugin/out_eventcounter.rb:90:in `each'
     # ./lib/fluent/plugin/out_eventcounter.rb:90:in `write'
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/compat/output.rb:129:in `write'
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/test/output_test.rb:94:in `block in run'
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/test/input_test.rb:124:in `block in run'
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/test/base.rb:71:in `run'
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/test/input_test.rb:123:in `run'
     # ./vednor/bundle/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/test/output_test.rb:76:in `run'
     # ./spec/out_eventcounter_spec.rb:104:in `block (3 levels) in <top (required)>'

Finished in 3.37 seconds (files took 0.79987 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/out_eventcounter_spec.rb:98 # Fluent::EventCounterOutput output formats the counts against the provided tag
```

**Comment by vijaykramesh** [comment]
sorry for the slow response! so I understand your intent, this is just updating things so it will work with Fluentd v0.12 and greater right? the label feature just comes via fluentd and doesn't need to be included in the plugin?

**Comment by vijaykramesh** [comment]
I'll merge your 3 PRs and release a new version of the gem shortly (merged one already, waiting for your response on this one and the other one). Thanks!

**Comment by cosmo0920** [comment]
> so I understand your intent, this is just updating things so it will work with Fluentd v0.12 and greater right?

Yes!



> the label feature just comes via fluentd and doesn't need to be included in the plugin?

Also, yes.

**Comment by vijaykramesh** [comment]
LGTM


thanks again, I'll build a new version of the gem momentarily

**Pull request merged**
